<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.akka</groupId>
        <artifactId>akka-javasdk-parent</artifactId>
        <version>3.6.0</version>
    </parent>
    <groupId>io.akka.mcp</groupId>
    <artifactId>akka-salesforce-mcp-server</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>akka-salesforce-mcp-server</name>

    <properties>
        <dockerImage>akka-salesforce-mcp-server</dockerImage>
        <docker.tag>${git.commit.id.abbrev}</docker.tag>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>4.9.10</version>
                <executions>
                    <execution>
                        <id>get-git-info</id>
                        <goals><goal>revision</goal></goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <configuration>
                    <shortAbbrevLength>8</shortAbbrevLength>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
