name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for git-commit-id-plugin

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run akka/github-actions-scripts
        uses: akka/github-actions-scripts/setup_global_resolver@main

      - name: Compile
        run: mvn compile --batch-mode

      - name: Test
        run: mvn test --batch-mode
